---

- name: nfs server installed
  register: nfs_kernel_server_installed
  package:
    name:
    - nfs-utils
    state: present

- name: copy file exports
  copy:
    src: "{{ nfs_file_export }}"
    dest: /etc/exports
    owner: root
    group: root
    mode: "u=r,g=r,o="
  notify:
  - reload-nfs

- name: nfs service is running as configured
  service:
    name: nfs_service
    state: "{{ nfs_service_state }}"
    enabled: "{{ nfs_service_enabled }}"
  notify:
  - reload-nfs

